Add missing handlers and templates for web based output
BonnyCI/quartermaster pull request #23
Opened 2017-03-01 20:17 UTC by pschwartz

Signed-off-by: Philip Marc Schwartz <philip@progmad.com>

2017-03-01 21:33 UTC, rattboi requested changes
Looks good other than my refactor suggestion

2017-03-01 21:33 UTC, rattboi commented on web/endpoints/status/status.go
> +	templates.Execute(w, nil)
These last 8 lines keep showing up. How about refactoring into a separate function?

2017-03-02 00:09 UTC, rattboi submitted a review, later dismissed
LGTM :+1:

2017-03-02 04:25 UTC, SpamapS submitted a review, later dismissed

2017-03-02 04:25 UTC, SpamapS commented on web/endpoints/status/status.go
> +// template loading adopted from https://elithrar.github.io/article/approximating-html-template-inheritance
The MIT license has to be included, in full, with any copies of the code. Luckily that's the only restriction, so Apache 2.0 can be applied on top of it (so the code is effectively dual-licensed). So what I'd suggest is putting the code in question in its own file with an MIT license header, or if you can't split it out, adding it right here under this comment.

2017-03-02 12:24 UTC, pschwartz commented
@rattboi @SpamapS Please re-review.

2017-03-02 18:11 UTC, rattboi approved these changes

2017-03-02 18:12 UTC, merged